[package]
name = "tb-core"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.40"
rstest = "0.23.0"
strum = "0.26"
strum_macros = "0.26"
os-version = "0.2.0"
log = "0.4.22"
simplelog = "^0.12.2"
which = "6.0.3"

[lib]
name = "tb_core"
path = "src/lib.rs"