[package]
name = "tb"
version = "0.1.0"
edition = "2021"

[dependencies]
tb-core = { path = "../tb-core" }
tb-builder = { path = "../tb-builder" }
tb-target-x86-64 = { path = "../tb-target-x86-64" }
log = "0.4.22"
simplelog = "^0.12.2"
